In [1]:
import numpy as np
import pandas as pd

In [5]:
arr=np.array(np.arange(10)).reshape(5,2)

arr+2

arr-2

array([[-2, -1],
       [ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7]])

In [15]:
arr2=np.array(np.arange(10)).reshape(2,5)

arr+arr

arr-arr

arr2@arr

array([[ 60,  70],
       [160, 195]])

In [19]:
arr1=np.array(np.arange(24)).reshape(2,3,4)

# arr1.reshape(4,3,2)
print(arr1)

print(arr1.shape)
print(arr1.ndim)

(3, 3)
2


In [22]:
mat=np.matrix(np.ones((3,3)))

mat=np.matrix(np.zeros((3,3)))

mat

matrix([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [44]:
arr=np.array([[1,2,3],
             [4,5,6]])

print(arr.reshape(3,2))

print(arr.flatten())

array([1, 2, 3, 4, 5, 6])

In [103]:
arr=np.array([[1,2,3],
             [4,5,6]])
arr2=np.array([2,3]).reshape(2,1)

# arr2.reshape(3,1)

print(np.append(arr,arr2,axis=1))

arr3=np.array([10,11,12]).reshape(1,3)

print(np.append(arr,arr3,axis=0))

[[1 2 3 2]
 [4 5 6 3]]
[[ 1  2  3]
 [ 4  5  6]
 [10 11 12]]


In [81]:
print(arr[0][1])

print(arr[0:,1:])

2
[[2 3]
 [5 6]]


In [93]:
print(
"max",np.max(arr)

,",min",np.min(arr)

,",mean",np.mean(arr)

,",median",np.median(arr)

,",standard deviation",np.std(arr))

max 6 ,min 1 ,mean 3.5 ,median 3.5 ,standard deviation 1.707825127659933


In [96]:
arr1=np.arange(10).reshape(2,5)
arr2=np.arange(10).reshape(5,2)

print(np.dot(arr1,arr2))

print(arr1@arr2)


[[ 60  70]
 [160 195]]
[[ 60  70]
 [160 195]]


In [104]:
arr5=np.array([[ 1 , 2 , 3],
 [ 4 , 5 , 6],
 [10, 11 ,12]])

np.linalg.eig(arr5)

(array([ 1.93923048e+01, -1.39230485e+00,  6.86419704e-16]),
 array([[ 0.19047623,  0.6835874 ,  0.40824829],
        [ 0.42237766,  0.22419772, -0.81649658],
        [ 0.88618052, -0.69458163,  0.40824829]]))

In [127]:
arr=np.arange(9).reshape(3,3)

print(np.linalg.det(arr))

inv=np.diag((1,1,1))

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

dict_values([1, 3])